spring:
  application:
    name: card-services/api
  boot:
    admin:
      url: http://localhost:8090

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{session.id}][%X{request.id}] %-5level %logger{36} - %msg%n%rEx{full, org.springframework.web, org.springframework.boot, org.apache.catalina, org.apache.coyote, org.apache.tomcat, java.base}"
  #        console: "%d{HH:mm:ss.SSS} [%thread] [%X{session.id}][%X{request.id}] %-5level %logger{36} - %msg%n"
  level:
    ROOT: ${vcap.services.variable-service.credentials.claimant-root-loglevel:info}
    uk.gov.dhsc: ${vcap.services.variable-service.credentials.claimant-app-loglevel:debug}

server:
  port: 8140

card-service:
  base-uri: ${CARD_SERVICES_API_URI:http://localhost:8120}
